# Generated by Django 2.1.3 on 2018-11-12 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='')),
                ('url_to_certificate', models.URLField(blank=True)),
                ('url_to_course', models.URLField(blank=True)),
                ('teachers', models.CharField(blank=True, max_length=256)),
                ('school', models.CharField(blank=True, max_length=256)),
                ('provider', models.CharField(blank=True, max_length=256)),
                ('date_of_earning', models.DateField(blank=True, null=True)),
                ('date_of_expiration', models.DateField(blank=True, null=True)),
                ('rank', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
    ]
